name: CI-CD_devoops 

on: 
  push:
    branches:
      - master

jobs:
  Test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./devops_lab3
    steps:
      - uses: actions/checkout@v4
      - run: |
          sudo apt-get update
          sudo apt-get install -y python3
          pip install pytest
      - run: |
          pytest test_main.py
  Deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./devops_lab3
    steps: 
      - uses: actions/checkout@v4
      - run: |
          sudo apt-get update
          sudo apt-get install -y python3
      - run: |
          echo "😈 BAD EXAMPLE"
          python helloworld.py
          
