name: bad ci/cd

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./DevOps/lab-3
    steps:
      - uses: actions/checkout@v3
      - run: |
          sudo apt-get update
          sudo apt-get install -y python3
          pip install pytest
      - run: pytest test.py

  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./DevOps/lab-3
    steps: 
      - uses: actions/checkout@v3
      - run: |
          sudo apt-get update
          sudo apt-get install -y python3
      - run: |
          echo "hi, I'm a bad guy"
          python hi.py
