name: good ci/cd

defaults:
  run:
    working-directory: ../lab-3

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-22.04
    steps: 
      - name: Check out
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
  
      - name: Install pytest
        run: pip install pytest
          
      - name: Run Test
        run: pytest test.py
          
  deploy:
    needs: test
    runs-on: ubuntu-22.04
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Deploy
        run: |
              echo "hi, I'm a good guy"
              python hi.py
