name: secrets

defaults:
  run:
    working-directory: ./DevOps/lab-3-star
    
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install Doppler CLI
        uses: dopplerhq/cli-action@v3

      - name: Sync secrets from Doppler
        run: |
          doppler secrets download --project="$DOPPLER_PROJECT" --config="$DOPPLER_CONFIG" --no-file
        env:
          DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN }}
          DOPPLER_PROJECT: ${{ secrets.DOPPLER_PROJECT }}
          DOPPLER_CONFIG: ${{ secrets.DOPPLER_CONFIG }}

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: npm run build

      - name: Deploy app
        run: ./deploy.sh
